server:
  port: 0

grpc:
  server:
    port: 9090 # TODO ClassNotFoundException: org.springframework.util.SocketUtils

spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.value}
      host: localhost
      port: 8500