server:
  port: 0
  servlet:
    context-path: /v1/grpc-client

spring:
  cloud:
    consul:
      discovery:
        health-check-path: ${server.servlet.context-path}/actuator/health
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.value}
      host: localhost
      port: 8500

grpc:
  client:
    GLOBAL:
      negotiation-type: plaintext

    hello-service:
      address: static://localhost:9090 # TODO Consul discovery is not working with Spring Boot 3